Add quantity button
WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team2 pull request #15
Opened 2022-11-05 09:55 UTC by o6ris

2022-11-07 08:27 UTC, jujuck requested changes

2022-11-07 08:27 UTC, jujuck commented on frontend/src/pages/OneProduct.jsx
> +import React, { useState } from "react";
Il y a 2 imports de React, pense à organiser tes imports (Les modules React en premier, puis les pages, puis les composants...)

2022-11-07 18:15 UTC, Chrisdu44 submitted a review, later dismissed

2022-11-07 18:15 UTC, Chrisdu44 commented on frontend/src/pages/OneProduct.jsx
> +import React, { useState } from "react";
done

2022-11-07 20:20 UTC, BarzaGuignol submitted a review, later dismissed
Ok pour moi

2022-11-08 15:26 UTC, jujuck requested changes

2022-11-08 15:26 UTC, jujuck commented on frontend/src/components/AddQuantity.jsx
> +    if (operator === "minus") {
Mettre les conditions dans le même "if"

2022-11-08 17:52 UTC, Chrisdu44 approved these changes

2022-11-09 08:08 UTC, BarzaGuignol approved these changes
C'est bon pour moi

2022-11-09 08:41 UTC, jujuck approved these changes

2022-11-09 08:41 UTC, merged