Progress bar
WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team2 pull request #16
Opened 2022-11-05 11:12 UTC by o6ris

Il s'agit de la version Mobile des progress bar. La version desktop ne pourra être faite qu'au moment où il faudra appeler le composant dans OneProduct. Là seulement on pourra créer des Div pour englober les composants entre eux et jouer avec les breakpoints

2022-11-07 10:23 UTC, kadev-oclock submitted a review, later dismissed

2022-11-07 18:03 UTC, Chrisdu44 submitted a review, later dismissed

2022-11-08 15:29 UTC, jujuck requested changes

2022-11-08 15:29 UTC, jujuck commented on frontend/src/components/ProgressBar.jsx
> +      <div className="d-flex flex-column align-items-start w-100">
Créer un sous composant avec la propriété en props

2022-11-08 17:45 UTC, o6ris commented on frontend/src/components/ProgressBar.jsx
> +      <div className="d-flex flex-column align-items-start w-100">
merci, ça a été fait !

2022-11-08 17:51 UTC, Chrisdu44 approved these changes

2022-11-08 18:34 UTC, kadev-oclock approved these changes
beaucoup de lignes en moins top :)

2022-11-09 07:55 UTC, jujuck approved these changes

2022-11-09 07:55 UTC, merged