Footer button
WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team2 pull request #28
Opened 2022-11-10 15:18 UTC by petaccia

boutons active pour envoie

2022-11-10 15:25 UTC, BarzaGuignol submitted a review, later dismissed
C'est bon pour moi

2022-11-10 16:10 UTC, o6ris submitted a review, later dismissed

2022-11-14 11:15 UTC, jujuck requested changes

2022-11-14 11:15 UTC, jujuck commented on frontend/src/components/ContactForm.jsx
> +function MyForm() {
Renomme ton composant en ContactForm comme le fichier

2022-11-16 07:10 UTC, o6ris reviewed
C'est bon pour moi !

2022-11-16 07:15 UTC, o6ris approved these changes
ok

2022-11-16 07:48 UTC, Chrisdu44 approved these changes

2022-11-16 08:50 UTC, jujuck approved these changes

2022-11-16 08:50 UTC, merged