Nav router
WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team2 pull request #33
Opened 2022-11-16 16:53 UTC by o6ris

2022-11-16 17:15 UTC, kadev-oclock submitted a review, later dismissed

2022-11-16 20:31 UTC, BarzaGuignol submitted a review, later dismissed
C'est bon pour moi

2022-11-17 07:00 UTC, jujuck requested changes

2022-11-17 07:00 UTC, jujuck commented on backend/package.json
> +    "react-toastify": "^9.1.1"
Pourquoi mettre react toastify en back.... STP npm uninstall react-toastify

2022-11-17 08:12 UTC, BarzaGuignol approved these changes
Ok

2022-11-17 08:25 UTC, Chrisdu44 approved these changes

2022-11-17 08:41 UTC, jujuck approved these changes

2022-11-17 08:42 UTC, merged