correctif carrousel : ajout nouveau carrousel version mobile
WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team2 pull request #34
Opened 2022-11-17 11:31 UTC by BarzaGuignol

correctif du carrousel en version mobile

2022-11-17 11:35 UTC, Chrisdu44 submitted a review, later dismissed

2022-11-17 11:48 UTC, o6ris approved these changes, later dismissed

2022-11-18 14:20 UTC, jujuck requested changes

2022-11-18 14:20 UTC, jujuck commented on package.json
> +  },
Les modules sont dans le front end et non en global, please  npm uninstall <package>

2022-11-18 14:37 UTC, o6ris approved these changes

2022-11-18 14:38 UTC, Chrisdu44 approved these changes

2022-11-18 15:19 UTC, jujuck approved these changes

2022-11-18 15:19 UTC, merged