Card bg color
WildCodeSchool/2022-09-JS-RMT-JSCREW-projet2-team2 pull request #42
Opened 2022-11-21 08:22 UTC by o6ris

2022-11-21 08:24 UTC, petaccia approved these changes, later dismissed

2022-11-21 08:24 UTC, Chrisdu44 approved these changes, later dismissed

2022-11-21 08:45 UTC, jujuck requested changes

2022-11-21 08:45 UTC, jujuck commented on frontend/src/components/TemplateCard.jsx
> +  const bgColorCards = [
Place ta variable en dehors de ta fonction (au dessus) comme un import

2022-11-21 08:45 UTC, jujuck commented on frontend/src/components/TemplateCard.jsx
> +    bgColorCards.filter(
Non, on ne fait pas de useState dans un filter... Met plutôt un find() en place et set le résultat

2022-11-21 09:09 UTC, Chrisdu44 approved these changes, later dismissed

2022-11-22 07:44 UTC, o6ris commented on frontend/src/components/TemplateCard.jsx
> +  const bgColorCards = [
C'est fait merci !

2022-11-22 07:46 UTC, o6ris commented on frontend/src/components/TemplateCard.jsx
> +    bgColorCards.filter(
Ok c'est fait j'ai mis un Find !
Par contre j'ai pas compris du coup pourquoi on ne peut pas utiliser de filter mais un find ?

2022-11-22 07:47 UTC, petaccia submitted a review, later dismissed

2022-11-22 07:52 UTC, jujuck requested changes

2022-11-22 07:52 UTC, jujuck commented on frontend/src/components/TemplateCard.jsx
> +    bgColorCards.find(
Non : setCardBgColor(bgColorCards.find(
      (bgColorCard) =>
        bgColorCard.type === pokemon.type.primary_type) On va mettre en state le résultat du find()

2022-11-22 08:42 UTC, Chrisdu44 approved these changes

2022-11-22 11:07 UTC, petaccia approved these changes

2022-11-22 11:29 UTC, jujuck approved these changes

2022-11-22 11:29 UTC, merged